### ISSUE TITLE
Can't change background colour

### ISSUE THREAD

**Issue by geazersb** [pages-themes/cayman#106]
hey, I am trying to change the background colour while using this theme.
I have looked in the code and can't find a variable that allows me to do this easily.
In my assets/css/style.css file I have added:

```scss
---
---

@import "{{ site.theme }}";

kbd {
  background-color: #d9dadb !important;
}
```

But that doesn't seem to change the background colour. 

How can I do this?

I can also not figure out how to add a favicon. I've looked at basically every article out there, they tell me to add something to the header in an html file. I don't have an HTML file though, and when I made a file to _layouts/default.html and added it there it did add the favicon, but it totally changed the the gradient/header on the top of the page.
