### ISSUE TITLE
Line numbering in code blocks is messy

### ISSUE THREAD

**Issue by Pamplemousse** [pages-themes/cayman#138]
By adding
```
kramdown:                                                                                                                                                                                          
   syntax_highlighter_opts:                                                                                                                                                                         
     block:                                                                                                                                                                                         
       line_numbers: true
```
to their Jekyll configuration, one can have line numbers displayed in code blocks.

However, I tried this with the cayman theme, and the display is messily overcomplicated.
This the following screenshot:
![Screenshot_2021-09-22_10-52-14](https://user-images.githubusercontent.com/2647236/134313525-9ddbf197-81bc-451d-adf3-8249a5c4227b.png)

I expected only to see the outermost border.
