### ISSUE TITLE
Buttons work OK on desktop, not on mobile

### ISSUE THREAD

**Issue by pippim** [pages-themes/cayman#141]
On the desktop buttons render well. Click the Play button to see Cayman style animation:

https://user-images.githubusercontent.com/92641463/138795813-8a104c47-2083-4834-b736-c0bc1f5992a3.mp4

On the mobile, not so good. I've seen some code in Cayman Theme to adapt to mobile but I don't know how to take advantage of it (small, medium and large screen). If I could just push the rest of Cayman DOWN somehow it might make this mobile image work:

![Screenshot_20211025-195441](https://user-images.githubusercontent.com/92641463/138795982-148bbbd9-3687-41ad-be2d-91485f697bf9.png)

I can shrink the desktop and mimic the mobile problems:

![pippim on small desktop](https://user-images.githubusercontent.com/92641463/138796395-6f7a5ce4-5ffa-4c86-ac46-114aeec84632.png)

The `_includes/head-custom.html` is pretty straight forward:

``` html
<!-- start custom head snippets, customize with your own _includes/head-custom.html file -->

<!-- Setup Google Analytics -->
{% include head-custom-google-analytics.html %}

<!-- Buttons to appear top of every page
      HOME - U+2302 - ⌂
      ABOUT - U+2753 - ❓
      ANSWERS - heavy check mark - U+2714 - ✓
      PROGRAMS - Unicode Character “💻” (U+1F4BB)
      EMAIL - Unicode Character “📧” (U+1F4E7)
-->
<div class="container">
  <a href="https://pippim.github.io/" style="display: inline" class="button">⌂ Home</a>
  <a href="about.html" style="display: inline" class="button">❓ About</a>
  <a href="answers.html" style="display: inline" class="button">✅ Answers</a>
  <a href="programs.html" style="display: inline" class="button">💻 Programs</a>
  <a href="mailto:pippim.com@gmail.com" style="display: inline" class="button">📧 Email</a>
</div>

<!-- You can set your favicon here -->
<!-- link rel="shortcut icon" type="image/x-icon" href="{{ '/favicon.ico' | relative_url }}" -->

<!-- end custom head snippets -->
```

The `assets/css/style.scss` is embarrassing (I only have 1 weekend experience):

``` css
---
---

@import "{{ site.theme }}";

// Headers (From: https://github.com/pages-themes/cayman/blob/master/_sass/variables.scss)
$header-heading-color: #fff !default;
$header-bg-color: #159957 !default;
$header-bg-color-secondary: #155799 !default;

.button {
  display: inline-block;
  padding: .75rem 1.25rem;
  border-radius: 10rem;
  color: #fff;
  border: 2px solid white;  // Added for Cayman
  font-size: .8rem;  // Try smaller font
  transition: all .3s;
  position: relative;
  overflow: hidden;
  z-index: 1;
  &:after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: $header-bg-color;  // For Cayman
    background-image: linear-gradient(120deg, $header-bg-color-secondary, $header-bg-color);
    border-radius: 10rem;
    z-index: -2;
  }
  &:before {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 0%;
    height: 100%;
    background-color: darken($header-bg-color-secondary, 1%);  // For Cayman
    transition: all .3s;
    border-radius: 10rem;
    z-index: -1;
  }
  &:hover {
    color: #fff;
    &:before {
      width: 100%;
    }
  }
}
.container {
  position: absolute;
  padding-top: 20px;  // Cayman
  margin: 0 auto;
  width: 100%;
  text-align: center;
}
span {
  display: block;
  margin-top: 2rem;
  font-size: .7rem;
  color: #777;
  a {
    font-size: .7rem;
    color: #999;
    text-decoration: underline;
  }
}
```

I'm hoping there is a quick fix here...
