### ISSUE TITLE
How do you disable the View on GitHub button? And edit footer?

### ISSUE THREAD

**Issue by miakurt** [pages-themes/cayman#79]
Sorry I am new. 
How do I remove View on GitHub button? And how do I remove in footer miakurt is maintained by miakurt.
This page was generated by GitHub Pages.
And how do I publish my page? Thank you.

**Comment by LuisEnMarroquin** [comment]
You can create a file in `assets/css/style.scss` and add the following lines

```scss
---
---

@import "{{ site.theme }}";

footer {
  display: none !important;
}

.btn {
  display: none !important;
}
```

Here's the [guide](https://guides.github.com/features/pages/) to publish your site
