### ISSUE TITLE
How to I add a background image in the header and a different background image for all my posts?

### ISSUE THREAD

**Issue by raghavsikaria** [pages-themes/cayman#89]
Hello Team,
Thank you so much for building and actively supporting such a wonderful theme!

I am new to this and am stuck with some basics. If this is not the right forum please excuse me and guide me to the correct one.

So, I want a _background image in the main header_ and different images for each of my posts, and all in **responsive way**.

I found this example on net: https://zachholman.com/ to really explain what I really want.

I have tried altering the value of background-image in /_sass/jekyll-theme-cayman.scss :

```
.page-header {
  color: $header-heading-color;
  text-align: center;
  background-color: $header-bg-color;
  background-image: url(../header_img.jpg);

  @include large {
    padding: 5rem 6rem;
  }

  @include medium {
    padding: 3rem 4rem;
  }

  @include small {
    padding: 2rem 1rem;
  }
}
```

This does place the header_img in the header bar, however, there are 2 problems:

1. The image is automatically cropped off somehow to fit the page and in the debugger in Chrome, I tried different responsive layouts: they all seem to crop somehow
2. The header image seems to persist for all posts, how to have a different one for all posts?

**Comment by raghavsikaria** [comment]
What it renders:

![image](https://user-images.githubusercontent.com/17681665/80913264-f67d3900-8d60-11ea-88f7-26aeaaea7c95.png)

What the image is:

![image](https://user-images.githubusercontent.com/17681665/80913282-2593aa80-8d61-11ea-92a4-0ec96841b7de.png)

And the debugger proves that in all layout renders - the image is not being responsive:

![image](https://user-images.githubusercontent.com/17681665/80913311-583da300-8d61-11ea-8e19-a6b2ad24a4cf.png)

**Comment by KTibow** [comment]
Use [`background-size`](https://css-tricks.com/almanac/properties/b/background-size/) to control the size. Use [`background-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position) to control alignment.

**Comment by KTibow** [comment]
It'd be pretty complex to have a different one for different posts...
Try
```css
.page-header {
  color: $header-heading-color;
  text-align: center;
  background-color: $header-bg-color;
  background-image: url(../header_img.jpg);
  background-size: 200% 100%;
  background-position: right;

  @include large {
    padding: 5rem 6rem;
  }

  @include medium {
    padding: 3rem 4rem;
  }

  @include small {
    padding: 2rem 1rem;
  }
}
```
